spring:
  application:
    name: CloudStorageDemo
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

server:
  port: 8081

jwt:
  secret:
    access: U0RTRkZkZ3Nuc2duc3RuZGZuZGZnbmRmZ25kZm5kZm5kZmduZGZuZA==
    refresh: YXNkZ2hzZXRodHJ3aGU2NTQ1NjMzbmRibiBkYXNyZ2VhcmdlcWE=

minio:
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

