version: '3'

volumes:
  minio-data:
    driver: local


services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cloud_storage
    ports:
      - "5432:5432"

